### ISSUE TITLE
Is this sdk support streaming response?

### ISSUE THREAD

**Issue by rpratama-codes** [devarshishimpi/google-gemini-nodejs-chatbot#1]
### What would you like to share?

Thankyou

**Comment by rpratama-codes** [comment]
i think, i found the answer, there stream parameter after selecting the model. thx

**Comment by devarshishimpi** [comment]
Hey! Really sorry with the delays, this is just a basic chatbot example to create with the Google Gemini API. However, if you wish to contribute with the solution you have found, feel free to re-open the issue for the same.
